In [5]:
import sys
from pathlib import Path

sys.path.append(str(Path("../src").resolve()))

In [40]:
#Descarga reproducible del Dataset
from inf8239_u01.data import download_dataset

URL = (
    "https://cdn.bancentral.gov.do/documents/"
    "otras-publicaciones/documents/"
    "Encuesta-Nacional-a-las-MIPYMES-2023-Base-de-datos.xlsx"
    "?v=1790336986063"
)

path = download_dataset(URL)

print(path)

C:\Users\oscarina.brazoban\Desktop\Maestria\INFP8239_U01\Laboratorio_02\data\raw\Encuesta-Nacional-a-las-MIPYMES-2023-Base-de-datos.xlsx

In [12]:
#Cargar y reproducir el dataset
import pandas as pd

df = pd.read_excel(
    "../data/raw/Encuesta-Nacional-a-las-MIPYMES-2023-Base-de-datos.xlsx"
)

print("Dimensiones:", df.shape)

print("\nTipos de datos:")
print(df.dtypes)

print("\nPrimeras filas:")
display(df.head())

print("\nÚltimas filas:")
display(df.tail())

assert not df.empty

Dimensiones: (13130, 126)

Tipos de datos:
ID                                                                                                             str
REGIÓN                                                                                                         str
PROVINCIA                                                                                                      str
RAMA DE ACTIVIDAD                                                                                              str
CLASIFICACIÓN MIPYMES                                                                                          str
                                                                                                            ...
P7_14_D - ¿POR QUÉ RAZONES LE RECHAZARON EL PRÉSTAMO O FINANCIAMIENTO SOLICITADO?: POSEE MUCHAS DEUDAS         str
P7_14_E - ¿POR QUÉ RAZONES LE RECHAZARON EL PRÉSTAMO O FINANCIAMIENTO SOLICITADO?: NO LE DIERON RAZONES        str
P7_14_F - ¿POR QUÉ RAZONES LE RECHAZARON EL PRÉSTAMO O FINANCIAMIENTO SOLICITADO?: OTROS (ESPECIFIQUE)         str
ESTATUS                                                                                                        str
FACTOR                                                                                                     float64
Length: 126, dtype: object

Primeras filas:

,ID,REGIÓN,PROVINCIA,RAMA DE ACTIVIDAD,CLASIFICACIÓN MIPYMES,FORMALIDAD,GRUPO DE EDAD DEL RESPONSABLE DE LA GESTIÓN DE LA EMPRESA,ÚLTIMO NIVEL DE ESTUDIO ALCANZADO POR EL RESPONSABLE DE LA GESTIÓN DE LA EMPRESA,INGRESOS TOTALES,COSTOS Y GASTOS OPERACIONALES,...,"P7_12 - ¿CUÁL ES LA RAZÓN PRINCIPAL POR LA QUE NO TOMARÍA ESTE PRÉSTAMO O FINANCIAMIENTO EN ALGUNA ENTIDAD FINANCIERA COMO BANCOS MÚLTIPLES, ASOCIACIONES, BANCO DE AHORROS Y CRÉDITOS, COOPERATIVA, ETC?","P7_13 - ¿ALGUNA VEZ LE HAN RECHAZADO UN PRÉSTAMO O FINANCIAMIENTO SOLICITADO EN ALGUNA ENTIDAD FINANCIERA (BANCOS MÚLTIPLES, ASOCIACIONES, BANCOS DE AHORROS Y CRÉDITO, COOPERATIVA, ETC.) PARA LA OPERACIÓN DE LA UNIDAD ECONÓMICA (NEGOCIO O EMPRESA)?",P7_14_A - ¿POR QUÉ RAZONES LE RECHAZARON EL PRÉSTAMO O FINANCIAMIENTO SOLICITADO?: NO POSEE CRÉDITO,P7_14_B - ¿POR QUÉ RAZONES LE RECHAZARON EL PRÉSTAMO O FINANCIAMIENTO SOLICITADO?: NO TIENE GARANTÍA,P7_14_C - ¿POR QUÉ RAZONES LE RECHAZARON EL PRÉSTAMO O FINANCIAMIENTO SOLICITADO?: NO TIENE COMO DEMOSTRAR SUS INGRESOS,P7_14_D - ¿POR QUÉ RAZONES LE RECHAZARON EL PRÉSTAMO O FINANCIAMIENTO SOLICITADO?: POSEE MUCHAS DEUDAS,P7_14_E - ¿POR QUÉ RAZONES LE RECHAZARON EL PRÉSTAMO O FINANCIAMIENTO SOLICITADO?: NO LE DIERON RAZONES,P7_14_F - ¿POR QUÉ RAZONES LE RECHAZARON EL PRÉSTAMO O FINANCIAMIENTO SOLICITADO?: OTROS (ESPECIFIQUE),ESTATUS,FACTOR
0,E1,Este,La Altagracia,Construcción,MEDIANA,Formal,40-59,Técnico Superior,1.097450e+08,26945000.0,...,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,Efectivas,7.500000
1,E2,Metropolitana,Santo Domingo,Industrias,MEDIANA,Formal,40-59,Universitaria,2.709949e+08,87723042.0,...,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,Efectivas,17.312500
2,E3,Norte,Duarte,Comercio,MEDIANA,Formal,40-59,Universitaria,1.324010e+08,72000000.0,...,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,Efectivas,53.785714
3,E4,Metropolitana,Distrito Nacional,"Suministro de alimentos, bebidas y alojamiento...",MEDIANA,Formal,40-59,Universitaria,1.480757e+08,98182282.0,...,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,Efectivas,8.800000
4,E5,Metropolitana,Santo Domingo,Salud y asistencia social,PEQUEÑA,Formal,60 o más,Secundaria,4.128605e+07,1686046.0,...,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,Efectivas,3.850000

Últimas filas:

,ID,REGIÓN,PROVINCIA,RAMA DE ACTIVIDAD,CLASIFICACIÓN MIPYMES,FORMALIDAD,GRUPO DE EDAD DEL RESPONSABLE DE LA GESTIÓN DE LA EMPRESA,ÚLTIMO NIVEL DE ESTUDIO ALCANZADO POR EL RESPONSABLE DE LA GESTIÓN DE LA EMPRESA,INGRESOS TOTALES,COSTOS Y GASTOS OPERACIONALES,...,"P7_12 - ¿CUÁL ES LA RAZÓN PRINCIPAL POR LA QUE NO TOMARÍA ESTE PRÉSTAMO O FINANCIAMIENTO EN ALGUNA ENTIDAD FINANCIERA COMO BANCOS MÚLTIPLES, ASOCIACIONES, BANCO DE AHORROS Y CRÉDITOS, COOPERATIVA, ETC?","P7_13 - ¿ALGUNA VEZ LE HAN RECHAZADO UN PRÉSTAMO O FINANCIAMIENTO SOLICITADO EN ALGUNA ENTIDAD FINANCIERA (BANCOS MÚLTIPLES, ASOCIACIONES, BANCOS DE AHORROS Y CRÉDITO, COOPERATIVA, ETC.) PARA LA OPERACIÓN DE LA UNIDAD ECONÓMICA (NEGOCIO O EMPRESA)?",P7_14_A - ¿POR QUÉ RAZONES LE RECHAZARON EL PRÉSTAMO O FINANCIAMIENTO SOLICITADO?: NO POSEE CRÉDITO,P7_14_B - ¿POR QUÉ RAZONES LE RECHAZARON EL PRÉSTAMO O FINANCIAMIENTO SOLICITADO?: NO TIENE GARANTÍA,P7_14_C - ¿POR QUÉ RAZONES LE RECHAZARON EL PRÉSTAMO O FINANCIAMIENTO SOLICITADO?: NO TIENE COMO DEMOSTRAR SUS INGRESOS,P7_14_D - ¿POR QUÉ RAZONES LE RECHAZARON EL PRÉSTAMO O FINANCIAMIENTO SOLICITADO?: POSEE MUCHAS DEUDAS,P7_14_E - ¿POR QUÉ RAZONES LE RECHAZARON EL PRÉSTAMO O FINANCIAMIENTO SOLICITADO?: NO LE DIERON RAZONES,P7_14_F - ¿POR QUÉ RAZONES LE RECHAZARON EL PRÉSTAMO O FINANCIAMIENTO SOLICITADO?: OTROS (ESPECIFIQUE),ESTATUS,FACTOR
13125,E13126,Metropolitana,Distrito Nacional,Enseñanza,MEDIANA,Formal,NaN,NaN,8.189010e+07,4.913406e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Imputado,13.000000
13126,E13127,Metropolitana,Distrito Nacional,Transporte y comunicaciones,MEDIANA,Formal,NaN,NaN,1.234578e+08,7.827478e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Imputado,17.285714
13127,E13128,Norte,Santiago,Construcción,MEDIANA,Formal,NaN,NaN,1.928130e+08,6.251382e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Imputado,4.583333
13128,E13129,Metropolitana,Distrito Nacional,Enseñanza,MEDIANA,Formal,NaN,NaN,2.626338e+08,1.937592e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Imputado,13.000000
13129,E13130,Norte,Santiago,Transporte y comunicaciones,MICRO,Informal,NaN,NaN,9.956567e+06,1.904408e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Imputado,6.408046

In [13]:
#Construir la auditoria
audit = pd.DataFrame({
    "tipo": df.dtypes.astype(str),
    "ausentes": df.isna().sum(),
    "porcentaje_ausente": (
        (df.isna().mean() * 100)
        .round(2)
    ),
    "unicos": df.nunique(dropna=False)
}).sort_values(
    "porcentaje_ausente",
    ascending=False
)

print("Duplicados:", df.duplicated().sum())

display(audit)

Duplicados: 0

,tipo,ausentes,porcentaje_ausente,unicos
P7_8- ¿QUÉ MEDIOS DE PAGO SE UTILIZARON DURANTE EL AÑO 2022 EN ESTE NEGOCIO O EMPRESA PARA REALIZAR SUS COMPRAS Y VENTAS?,float64,13130,100.00,1
P5_6_1 - ESPECIFIQUE A QUE PIENSA DEDICARSE,str,13035,99.28,93
"P7_12 - ¿CUÁL ES LA RAZÓN PRINCIPAL POR LA QUE NO TOMARÍA ESTE PRÉSTAMO O FINANCIAMIENTO EN ALGUNA ENTIDAD FINANCIERA COMO BANCOS MÚLTIPLES, ASOCIACIONES, BANCO DE AHORROS Y CRÉDITOS, COOPERATIVA, ETC?",str,12867,98.00,8
P5_6 - ¿QUÉ PIENSA HACER O A QUÉ PIENSA DEDICARSE?,str,12627,96.17,6
P7_7_1 - ESPECIFIQUE EL OTRO MOTIVO PRINCIPAL POR EL CUAL LA EMPRESA NO TUVO ALGUNA CUENTA BANCARIA,str,12624,96.15,457
...,...,...,...,...
TOTAL DE EMPLEADORES (DUEÑOS O PROPIETARIOS FUERA DE NÓMINA),int64,0,0.00,22
TOTAL PERSONAL COMISIONISTA,int64,0,0.00,18
TOTAL PERSONAL TEMPORERO,int64,0,0.00,30
ESTATUS,str,0,0.00,2
FACTOR,float64,0,0.00,114

In [15]:
#Limpieza de los espacios en los nombres de las columnas
df.columns = df.columns.str.strip()

In [16]:
#Definir target y retirar fugas
TARGET = "FORMALIDAD"

DROP_COLUMNS = []

assert TARGET in df.columns

X = df.drop(columns=[TARGET] + DROP_COLUMNS)
y = df[TARGET]

print(y.value_counts(dropna=False))

assert y.notna().all()
assert y.nunique() >= 2

FORMALIDAD
Informal    7482
Formal      5648
Name: count, dtype: int64

In [18]:
#Verificar las variables categóricas y numéricas
print("Variables numéricas:")
print(X.select_dtypes(include="number").shape[1])

print("Variables categóricas:")
print(X.select_dtypes(exclude="number").shape[1])

Variables numéricas:
27
Variables categóricas:
98

In [21]:
#Separar tipos y crear el procesamiento de datos
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

num_cols = X.select_dtypes(
    include="number"
).columns.tolist()

cat_cols = X.select_dtypes(
    exclude="number"
).columns.tolist()

num_pipe = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scale", StandardScaler())
])

cat_pipe = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocess = ColumnTransformer([
    ("num", num_pipe, num_cols),
    ("cat", cat_pipe, cat_cols)
])

print(len(num_cols), len(cat_cols))

27 98

In [22]:
#Dividir, baseline y SVM
from sklearn.model_selection import train_test_split
from sklearn.dummy import DummyClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report, f1_score

Xtr, Xte, ytr, yte = train_test_split(
    X,
    y,
    test_size=.20,
    random_state=42,
    stratify=y
)

dummy = Pipeline([
    ("prep", preprocess),
    ("model", DummyClassifier(strategy="most_frequent"))
])

svm = Pipeline([
    ("prep", preprocess),
    ("model", SVC(
        gamma="scale",
        probability=True,
        random_state=42
    ))
])

for name, model in {
    "dummy": dummy,
    "svm": svm
}.items():

    model.fit(Xtr, ytr)

    pred = model.predict(Xte)

    print(
        name,
        f1_score(
            yte,
            pred,
            average="macro"
        )
    )

print(
    classification_report(
        yte,
        svm.predict(Xte)
    )
)

c:\Users\oscarina.brazoban\Desktop\Maestria\INFP8239_U01\.venv\Lib\site-packages\sklearn\impute\_base.py:647: UserWarning: Skipping features without any observed values: ['P7_8- ¿QUÉ MEDIOS DE PAGO SE UTILIZARON DURANTE EL AÑO 2022 EN ESTE NEGOCIO O EMPRESA PARA REALIZAR SUS COMPRAS Y VENTAS?']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
c:\Users\oscarina.brazoban\Desktop\Maestria\INFP8239_U01\.venv\Lib\site-packages\sklearn\impute\_base.py:647: UserWarning: Skipping features without any observed values: ['P7_8- ¿QUÉ MEDIOS DE PAGO SE UTILIZARON DURANTE EL AÑO 2022 EN ESTE NEGOCIO O EMPRESA PARA REALIZAR SUS COMPRAS Y VENTAS?']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
c:\Users\oscarina.brazoban\Desktop\Maestria\INFP8239_U01\.venv\Lib\site-packages\sklearn\impute\_base.py:647: UserWarning: Skipping features without any observed values: ['P7_8- ¿QUÉ MEDIOS DE PAGO SE UTILIZARON DURANTE EL AÑO 2022 EN ESTE NEGOCIO O EMPRESA PARA REALIZAR SUS COMPRAS Y VENTAS?']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

dummy 0.36293061620572536

c:\Users\oscarina.brazoban\Desktop\Maestria\INFP8239_U01\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
c:\Users\oscarina.brazoban\Desktop\Maestria\INFP8239_U01\.venv\Lib\site-packages\sklearn\impute\_base.py:647: UserWarning: Skipping features without any observed values: ['P7_8- ¿QUÉ MEDIOS DE PAGO SE UTILIZARON DURANTE EL AÑO 2022 EN ESTE NEGOCIO O EMPRESA PARA REALIZAR SUS COMPRAS Y VENTAS?']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

svm 0.8697748781557029

c:\Users\oscarina.brazoban\Desktop\Maestria\INFP8239_U01\.venv\Lib\site-packages\sklearn\impute\_base.py:647: UserWarning: Skipping features without any observed values: ['P7_8- ¿QUÉ MEDIOS DE PAGO SE UTILIZARON DURANTE EL AÑO 2022 EN ESTE NEGOCIO O EMPRESA PARA REALIZAR SUS COMPRAS Y VENTAS?']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

              precision    recall  f1-score   support

      Formal       0.94      0.76      0.84      1130
    Informal       0.84      0.96      0.90      1496

    accuracy                           0.88      2626
   macro avg       0.89      0.86      0.87      2626
weighted avg       0.88      0.88      0.87      2626